# Date: July 31, 2022
# Description: A simple stack that creates a VPC and some subnets. Some values may
# be hard-coded into this stack, modification when reuse is highly encouraged.
AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  A simple stack that creates a VPC that spans two availability zones. Two public subnets
  and two private subnets will be provisioned in this VPC.
Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: "^([0-9]{1,3}\\.){3}[0-9]\\/[0-9]{2}$"
  VpcInstanceTenancy:
    Type: String
    Default: "default"
    AllowedValues:
      - "default"
      - "dedicated"
  Subnet1AZ:
    Type: AWS::EC2::AvailabilityZone::Name
  Subnet2AZ:
    Type: AWS::EC2::AvailabilityZone::Name
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true,
      EnableDnsSupport: true,
      InstanceTenancy: !Ref VpcInstanceTenancy
      Tags:
        - Key: "stack"
          Value: "vpc-stack-simple"
