# Date: July 31, 2022
# Description: A simple stack that creates a VPC and some subnets. Some values may
# be hard-coded into this stack, modification when reuse is highly encouraged.
AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  A simple stack that creates a VPC that spans two availability zones. Two public subnets
  and two private subnets will be provisioned in this VPC.
Metadata:
  Author: Jimmy Lan
  Version: "2022-07-31"
  Purpose: "VPC baseline"
Parameters:
  VpcName:
    Type: String
    Default: "My VPC"
    MaxLength: 50
    Description: >-
      (Optional) Name of this VPC.
  VpcCidr:
    Type: String
    Default: "10.0.0.0/16"
    AllowedPattern: "^([0-9]{1,3}\\.){3}[0-9]\\/[0-9]{2}$"
    Description: "*(Required) CIDR block that this VPC uses."
  VpcInstanceTenancy:
    Type: String
    Default: "default"
    AllowedValues:
      - "default"
      - "dedicated"
    Description: "*(Required) Tenancy of instances in this VPC."
  VpcSubnetAzs:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: >-
      *(Required) Availability zones that this VPC spans across. Note: This simple stack only supports two
      availability zones. Please select exactly two availability zones - one public and one private subnet
      will be provisioned in each AZ that you select. If you select more than two AZs, only the first two
      will be used. If you select less than two AZs, an error will be thrown.
  PublicSubnet1Cidr:
    Type: String
    Default: "10.0.0.0/20"
    Description: "*(Required) CIDR block for **Public** Subnet 1 residing in the first AZ."
    AllowedPattern: "^([0-9]{1,3}\\.){3}[0-9]\\/[0-9]{2}$"
  PrivateSubnet1Cidr:
    Type: String
    Default: "10.0.16.0/20"
    Description: "*(Required) CIDR block for **Private** Subnet 1 residing in the first AZ."
    AllowedPattern: "^([0-9]{1,3}\\.){3}[0-9]\\/[0-9]{2}$"
  PublicSubnet2Cidr:
    Type: String
    Default: "10.1.0.0/20"
    Description: "*(Required) CIDR block for **Public** Subnet 2 residing in the first AZ."
    AllowedPattern: "^([0-9]{1,3}\\.){3}[0-9]\\/[0-9]{2}$"
  PrivateSubnet2Cidr:
    Type: String
    Default: "10.1.16.0/20"
    Description: "*(Required) CIDR block for **Private** Subnet 2 residing in the first AZ."
    AllowedPattern: "^([0-9]{1,3}\\.){3}[0-9]\\/[0-9]{2}$"
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true,
      EnableDnsSupport: true,
      InstanceTenancy: !Ref VpcInstanceTenancy
      Tags:
        - Key: "stack"
          Value: "vpc-stack-simple"
